### ISSUE TITLE
TensorFlow 2.10.0 cannot be installed on Python 2.7.5.

### ISSUE THREAD

**Issue by braahkrayem** [MMTI/Toolkit_for_MIRA_LAB_Striatal_Segmentation#3]
I am trying to run the project using the versions specified in the documentation:

Python: 2.7.5
TensorFlow: 2.10.0
Numpy: 1.23.2
Nibabel: 4.0.2
Scipy: 1.9
However, I encountered issues since these versions (e.g., TensorFlow 2.10.0 and Numpy 1.23.2) are incompatible with Python 2.7. TensorFlow 2.x requires Python 3.7 or above.
Can you clarify which Python version the project is intended to use?
Are the listed library versions correct for this project? If not, can you provide the proper versions?
If Python 2.7.5 is mandatory, what are the compatible versions of TensorFlow, Numpy, and other dependencies?

**Comment by yashpat016** [comment]
Hi @braahkrayem 

Thanks for bringing this to our attention and I apologize for the confusion caused by the outdated documentation. You’re spot-on: TensorFlow 2.10.0 is not compatible with Python 2.7.x neither is Numpy or Scipy I believe. 

Here are the updated versions that you should use for this project (also what the Striatal Segmentation has been tested with, apart from the python version the rest is correct):

1. Python 3.9.14 (I would recommend  3.8 or later as it provides best compatibility with other libraries)
2. Tensorflow 2.10.0
3. Numpy 1.23.2
4. Nibble 4.0.2
5. Scipy 1.9.1

I will update the markdown to reflect the correct python version to prevent future confusion. Thank you for your patience and for catching that mistake!

If you encounter any further issues or have additional questions, please feel free to reach out.

Regards,
Yash
